import mongoose, { Schema, model } from 'mongoose'; // Import Mongoose and the types needed for schema creation

interface IResumeReport {
  name?: string;
  matchScore?: number;
  jobDescription: string; // Text of the job description used for the resume review
  resumeText: string; // Full resume content provided by the user
  selfDescription: string; // User's self-description or summary section

  overallScore: {
    score: number; // Numeric score representing overall resume quality
  };

  technicalQuestions: {
    question: string; // Technical interview question generated by the report
    intention: string; // Why the question is asked or what it evaluates
    answer: string; // Recommended answer or evaluation text
  }[]; // Array of technical question objects

  behavioralQuestions: {
    question: string; // Behavioral interview question generated by the report
    intention: string; // The intent behind the behavioral question
    answer: string; // Recommended answer or evaluation text
  }[]; // Array of behavioral question objects

  skillsGaps: {
    skill: string; // Skill the resume is missing or needs improvement
    severity: 'low' | 'medium' | 'high'; // Severity level of the gap
  }[]; // Array of skill gap objects

  preparationPlan: {
    day: number; // Day number in the preparation plan
    resources: string[]; // Learning resources or links for that day
    focusAreas: string[]; // Topics to focus on for that day
    tasks: string[]; // Action items or practice tasks for that day
  }[]; // Array of preparation plan entries

  user: {
    type: string,
    ref: string
  }
}

const resumeReportSchema = new Schema<IResumeReport>(
  {
    name: { type: String },
    matchScore: { type: Number },
    resumeText: { type: String }, // Resume text is optional but recommended
    selfDescription: { type: String }, // Optional self-description text,
    technicalQuestions: [
      {
        question: { type: String, }, // Required technical question text
        intention: { type: String, }, // Required explanation of the question intent
        answer: { type: String, }, // Required answer or guidance text
      },
    ],
    jobDescription: { type: String, }, // Required job description text
    behavioralQuestions: [
      {
        question: { type: String, }, // Required behavioral question text
        intention: { type: String, }, // Required explanation of the question intent
        answer: { type: String, }, // Required answer or guidance text
      },
    ],
    skillsGaps: [
      {
        skill: { type: String }, // Required name of the missing or weak skill
        severity: { type: String, enum: ['low', 'medium', 'high'] },
      },
    ],
    preparationPlan: [
      {
        day: { type: Number, }, // Day index for plan entry
        resources: { type: [String], }, // Required list of resource strings
        focusAreas: { type: [String], }, // Required focus area names
        tasks: { type: [String], }, // Required list of tasks
      },
    ],
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "users"
    }
  },
  { timestamps: true } // Automatically add createdAt and updatedAt fields
);

export const resumeReportModel = model<IResumeReport>('ResumeReport', resumeReportSchema); // Export the model for use in the app
